version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    create_environment:
      - echo "Preparing environment"
    install:
      - echo "Installing dependencies"
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - uv run --group docs sphinx-build -W -b dirhtml docs $READTHEDOCS_OUTPUT/html
